name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for [skip-ci] or [no-cicd] in commit message
        id: check-skip
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ \[skip-ci\]|\[no-cicd\]|\[skip\ ci\]|\[ci\ skip\] ]]; then
            echo "skip_ci=true" >> $GITHUB_OUTPUT
            echo "⏭️ CI/CD skipped due to commit message flag"
          else
            echo "skip_ci=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Bun
        if: steps.check-skip.outputs.skip_ci == 'false'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        if: steps.check-skip.outputs.skip_ci == 'false'
        run: bun install

      - name: Build application
        if: steps.check-skip.outputs.skip_ci == 'false'
        run: bun run build

      - name: Configure AWS credentials
        if: steps.check-skip.outputs.skip_ci == 'false'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Deploy to S3 + CloudFront
        if: steps.check-skip.outputs.skip_ci == 'false'
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          chmod +x ./.github/scripts/deploy-to-aws.sh
          ./.github/scripts/deploy-to-aws.sh "reskill-ks"
